name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  format:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install formatting tools
        run: |
          brew update
          brew install clang-format cppcheck

      - name: Check code format
        run: make check_format


  build:
    runs-on: macos-latest
    needs: format

    steps:
      - uses: actions/checkout@v3

      - name: Install build tools
        run: |
          brew update
          brew install cmake ninja

      - name: Setup vcpkg (with cache)
        uses: friendlyanon/setup-vcpkg@v1
        with:
          committish: master
          path: vcpkg
          cache-key: vcpkg-${{ runner.os }}-${{ hashFiles('vcpkg.json', 'vcpkg-configuration.json') }}

      - name: Build project
        run: |
          COVERAGE=1 make build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-folder
          path: build


  test:
    runs-on: macos-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Install build tools
        run: |
          brew update
          brew install cmake ninja llvm

      - name: Add LLVM tools to PATH
        run: |
          echo "$(brew --prefix llvm)/bin" >> $GITHUB_PATH

      - name: Setup vcpkg (restore-only)
        uses: friendlyanon/setup-vcpkg@v1
        with:
          committish: master
          path: vcpkg
          cache-key: vcpkg-${{ runner.os }}-${{ hashFiles('vcpkg.json', 'vcpkg-configuration.json') }}
          skip-save: "true"

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-folder
          path: build

      - name: Run unit tests
        run: |
          COVERAGE=1 make tests
    
    

  coverage:
    runs-on: macos-latest
    needs: test

    steps:
      - uses: actions/checkout@v3

      - name: Install LLVM for coverage tools
        run: |
          brew update
          brew install llvm

      - name: Add LLVM to PATH
        run: echo "/opt/homebrew/opt/llvm/bin" >> $GITHUB_PATH

      - name: Setup vcpkg (restore-only)
        uses: friendlyanon/setup-vcpkg@v1
        with:
          committish: master
          path: vcpkg
          cache-key: vcpkg-${{ runner.os }}-${{ hashFiles('vcpkg.json', 'vcpkg-configuration.json') }}
          skip-save: "true"

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-folder
          path: build

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: build/coverage.lcov
          fail_ci_if_error: true
