name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  format:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies for formatting
        run: |
          if ! command -v brew &> /dev/null; then
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          fi
          brew update
          brew install clang-format cppcheck
      - name: Check code format
        run: make check_format

  build:
    runs-on: macos-latest
    needs: format
    steps:
      - uses: actions/checkout@v3
      - name: Fetch tinyobjloader
        run: |
          mkdir -p external
          git clone https://github.com/tinyobjloader/tinyobjloader.git external/tinyobjloader
      - name: Install build dependencies
        run: |
          if ! command -v brew &> /dev/null; then
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          fi
          brew update
          brew install cmake ninja llvm glm sdl3 googletest nlohmann-json
      - name: Build project
        run: make build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-folder
          path: build

  test:
    runs-on: macos-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Install build dependencies
        run: |
          if ! command -v brew &> /dev/null; then
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          fi
          brew update
          brew install cmake ninja llvm glm sdl3 googletest nlohmann-json
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-folder
          path: build
      - name: Run unit tests (with coverage)
        run: |
          COVERAGE=1 make tests

  coverage:
    runs-on: macos-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Install coverage tools
        run: |
          if ! command -v brew &> /dev/null; then
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          fi
          brew update
          brew install llvm

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-folder
          path: build

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: build/coverage.lcov
          fail_ci_if_error: true
